on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Compile
        run: mvn clean compile -e
      - name: Testing
        run: mvn test -e
